"""Adding ProvinceDBModelConfig

Revision ID: 818bb1d09879
Revises: 442b048ecd70
Create Date: 2023-07-16 15:36:31.474256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818bb1d09879'
down_revision = '442b048ecd70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
