"""Adding ProvinceDBModelConfig

Revision ID: 2eea18cbb7ea
Revises: 8bc6990e755d
Create Date: 2023-07-16 12:01:01.384331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eea18cbb7ea'
down_revision = '8bc6990e755d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
