"""Adding CityDBModelConfig

Revision ID: 8bc6990e755d
Revises: 
Create Date: 2023-07-16 12:00:18.502168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc6990e755d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provinces',
    sa.Column('province_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('province_id')
    )
    op.create_table('cities',
    sa.Column('city_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.province_id'], ),
    sa.PrimaryKeyConstraint('city_id'),
    sa.UniqueConstraint('city_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    op.drop_table('provinces')
    # ### end Alembic commands ###
