"""Adding CityDBModel

Revision ID: 78f34f0bc9ce
Revises: ccaa96145c72
Create Date: 2023-07-10 12:07:47.583686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f34f0bc9ce'
down_revision = 'ccaa96145c72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
